# -*- coding: utf-8 -*-
"""new_ui_test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UyeJjf8Nro418CaZmbO2bxRrftptmsgu
"""

import streamlit as st
from PIL import Image
import base64

# ------------------------ PAGE CONFIG ------------------------
st.set_page_config(
    page_title="Binding Affinity Predictor",
    layout="wide",
    page_icon="🧬"
)

# ------------------------ CUSTOM CSS ------------------------
st.markdown("""
    <style>
        body {
            background-color: #0f0f0f;
            color: #e0e0e0;
            font-family: 'Segoe UI', sans-serif;
        }
        .main {
            background-color: #0f0f0f;
        }
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
        }
        .css-1v0mbdj, .stButton>button {
            background-color: #222;
            color: white;
            border-radius: 10px;
            transition: all 0.3s ease;
        }
        .stButton>button:hover {
            background-color: #1a1a1a;
            transform: scale(1.03);
        }
        .suggestion-card {
            background-color: #1c1c1c;
            padding: 1rem;
            border-left: 5px solid #06d6a0;
            margin-top: 20px;
            border-radius: 10px;
        }
        .dna-icon {
            height: 50px;
            margin-right: 10px;
        }
    </style>
""", unsafe_allow_html=True)

# ------------------------ HEADER ------------------------
st.markdown("## 🧬 Binding Affinity Predictor")
st.markdown("---")

# ------------------------ LAYOUT ------------------------
col1, col2 = st.columns([1, 2])

with col1:
    st.image("https://cdn-icons-png.flaticon.com/512/3004/3004496.png", width=80)
    st.markdown("### Upload Compound & Target Info")
    uploaded_file = st.file_uploader("Upload your molecule file", type=["sdf", "mol2", "pdbqt"])

with col2:
    st.markdown("### Description")
    st.write("This tool predicts binding affinity between a target and compound using ML models. "
             "Designed for drug discovery researchers. Styled with 🔥 aesthetics.")

# ------------------------ AI PREDICTION OUTPUT ------------------------
predicted = True  # Simulate prediction done

if predicted:
    st.markdown("### 🔍 Prediction Result")
    st.success("Binding affinity score: **-8.21 kcal/mol**")

    # Suggestion card
    st.markdown("""
        <div class='suggestion-card'>
            <h4>🧠 AI Suggestion:</h4>
            <p>Compound shows high affinity for TNF target. May be worth testing for inflammatory pathways.</p>
        </div>
    """, unsafe_allow_html=True)

# ------------------------ FOOTER / CREDITS ------------------------
st.markdown("---")
st.markdown("Built with 💡 by [Your Name]")